# Change baseurl before deploy
baseurl = "http://frospon.top/"
locale = "en-us"
title = "冰茶FrostyT's Blog"
copyright = "FrostyT's Blog"

# Theme i18n support
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

[pagination]
    pagerSize = 6

# 远程资源缓存立即过期，确保每次构建都获取最新的多邻国连胜数据
[caches]
    [caches.getresource]
        dir = ':cacheDir/:project'
        maxAge = '0s'
