[zh]
    label = "简体中文"
    title = "冰茶FrostyT's Blog"
    weight = 1

    [zh.params]
        description = "演示说明"

[zh-hant-hk]
    label = "粤语"
    title = "FrostyT's Blog"
    weight = 2

    [zh-hant-hk.params]
        description = "演示說明"
